on:
  push:
    branches:
      - main
    paths:
      - protoc-gen-openapiv2/options/*.proto
permissions:
  contents: read
name: main
jobs:
  proto_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4
        with:
          check-latest: true
      - run: make install
      # Limit pushes to protoc-gen-openapiv2 files. This is a total hack.
      # It excludes all the files that we don't want to publish, just for the push step.
      - run: echo -e "    - examples\n    - internal\n    - runtime" >> buf.yaml
      - run: buf push --tag "${{ github.sha }}"
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
          PATH: $PATH:~/go/bin
